// apps/dashboard/src/components/UploadProgressWidget.vue
<template>
  <div
    class="upload-progress-bars panel panel-warning"
    :class="{
      'upload-progress-bars-hidden': uploadProgressStore.records.length === 0,
    }"
  >
    <div class="panel-heading">Upload Progress</div>
    <div class="panel-body upload-progress-panel-body">
      <div
        v-for="record in uploadProgressStore.records"
        :key="record.id"
        class="progress-item"
      >
        <div v-if="record.error" class="progress-error">
          <div class="alert alert-danger upload-alert">
            <button
              type="button"
              class="close"
              aria-label="Close"
              @click="uploadProgressStore.removeRecord(record.id)"
            >
              <span aria-hidden="true">&times;</span>
            </button>
            <b>{{ record.filename }}</b
            ><br />
            {{ record.message }}
          </div>
        </div>
        <div v-else class="progress">
          <div
            class="progress-bar"
            :id="record.id"
            role="progressbar"
            aria-valuenow="0"
            aria-valuemin="0"
            aria-valuemax="100"
            :style="{ width: '0%' }"
          >
            <span class="percent">0%</span> - {{ record.filename }}
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { useUploadProgressStore } from "@/stores/uploadProgressStore";

// Use the upload progress store instead of local state
const uploadProgressStore = useUploadProgressStore();

// Generate a random ID for each upload
const randomID = () => {
  return "upload-" + Math.random().toString(36).substring(2, 15);
};

// Upload a file
// Args:
//  uploadRequestPath: the upload HTTP request path
//  file: the javascript File object
//  dest: destination filename, set to undefined if sid is set
//  sid: terminal session ID, used to identify upload destination
//  done: callback to execute when upload is completed
const upload = (uploadRequestPath, file, dest, sid, done) => {
  // Use the store's upload method instead
  uploadProgressStore.upload(uploadRequestPath, file, dest, sid, done);
};

// Expose the upload method for backwards compatibility
defineExpose({
  upload,
});
</script>

<style scoped>
.upload-progress-bars {
  position: fixed;
  bottom: 20px;
  right: 20px;
  width: 500px;
  z-index: 1000;
  background-color: rgba(15, 23, 42, 0.95);
  border-radius: 0.5rem;
  box-shadow:
    0 10px 15px -3px rgba(0, 0, 0, 0.2),
    0 4px 6px -2px rgba(0, 0, 0, 0.1),
    0 0 0 1px rgba(16, 185, 129, 0.2);
  max-height: 500px;
  overflow-y: auto;
  color: #e5e7eb;
  border: 1px solid rgba(51, 65, 85, 0.5);
}

.upload-progress-bars-hidden {
  display: none;
}

.panel-heading {
  background-color: rgba(16, 185, 129, 0.2);
  color: #e5e7eb;
  padding: 10px 15px;
  border-top-left-radius: 0.5rem;
  border-top-right-radius: 0.5rem;
  font-weight: bold;
  border-bottom: 1px solid rgba(51, 65, 85, 0.5);
}

.panel-body {
  padding: 15px;
}

.progress {
  margin-bottom: 10px;
  height: 30px;
  border-radius: 0.25rem;
  background-color: rgba(51, 65, 85, 0.3);
  overflow: hidden;
}

.progress-bar {
  display: flex;
  align-items: center;
  justify-content: flex-start;
  padding-left: 10px;
  height: 100%;
  background-color: rgba(16, 185, 129, 0.7);
  color: #e5e7eb;
  transition: width 0.3s ease;
}

.progress-error .alert {
  background-color: rgba(239, 68, 68, 0.2);
  color: #e5e7eb;
  border: 1px solid rgba(239, 68, 68, 0.5);
  padding: 10px;
  margin-bottom: 10px;
  border-radius: 0.25rem;
}

.progress-error .close {
  color: #e5e7eb;
  opacity: 0.7;
  background: none;
  border: none;
  float: right;
  font-size: 1.5rem;
  font-weight: 700;
  line-height: 1;
  padding: 0;
  cursor: pointer;
}

.progress-error .close:hover {
  opacity: 1;
}

@media (max-width: 768px) {
  .upload-progress-bars {
    width: calc(100% - 40px);
    left: 20px;
  }
}
</style>

// go/src/overlord/app/common/js/UploadProgressWidget.jsx
// Copyright 2016 The Chromium OS Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
//
// View for TerminalWindow:
// - UploadProgressWidget
//   - [(ProgressBar|ProgressBar) ...]

var UploadProgressWidget = React.createClass({
  getInitialState: function () {
    return {records: []};
  },
  // Perform upload
  // Args:
  //  uploadRequestPath: the upload HTTP request path
  //  file: the javascript File object
  //  dest: destination filename, set to "undefined" if sid is set
  //  sid: terminal session ID, use to identify upload destionation
  //  done: callback to execute when upload is completed
  upload: function (uploadRequestPath, file, dest, sid, done) {
    var $this = this;
    var query = "?";

    if (typeof(sid) != "undefined") {
      query += "terminal_sid=" + sid;
    }

    if (typeof(dest) != "undefined") {
      query += "&dest=" + dest;
    }

    function postFile(file) {
      var id = randomID();
      var formData = new FormData();
      formData.append("file", file);

      $this.addRecord({filename: file.name, id: id});
      $.ajax({
        xhr: function () {
          var xhr = new window.XMLHttpRequest();
          xhr.upload.addEventListener("progress", function (event) {
            if (event.lengthComputable) {
              var percentComplete = Math.round(event.loaded * 100 /
                                               event.total);
              $("#" + id).css("width", percentComplete + "%");
              $("#" + id + " > .percent").text(percentComplete + "%");
            }
          }, false);
          return xhr;
        },
        url: uploadRequestPath + query,
        data: formData,
        cache: false,
        contentType: false,
        processData: false,
        type: "POST",
        success: function (data) {
          $("#" + id).css("width", "100%");
          // Display the progressbar for 1 more seconds after complete.
          setTimeout(function () {
            $this.removeRecord(id);
          }.bind(this), 1000);
        },
        complete: function () {
          // Execute done callback
          if (typeof(done) != "undefined") {
            done();
          }
        },
        error: function (data) {
          var response = JSON.parse(data.responseText);
          $this.addRecord(
              {error: true, filename: file.name, id: id,
                message: response.error});
          setTimeout(function () {
            $this.removeRecord(id);
          }.bind(this), 1000);
        }
      });
    };

    // Send GET to the API to do pre-check
    $.ajax({
      url: uploadRequestPath + query + "&filename=" + file.name,
      success: function (file) {
        return function (data) {
          // Actually upload the file
          postFile(file);
        };
      }(file),
      error: function (file) {
        return function (data) {
          var id = randomID();
          var response = JSON.parse(data.responseText);

          $this.addRecord(
              {error: true, filename: file.name, id: id,
               message: response.error});
        }
      }(file),
      type: "GET"
    });
  },
  addRecord: function (record) {
    this.setState(function (state, props) {
      state.records.push(record);
    });
  },
  removeRecord: function (id) {
    this.setState(function (state, props) {
      var index = state.records.findIndex(function (el, index, array) {
        return el.id == id;
      });
      if (index !== -1) {
        state.records.splice(index, 1);
      }
    });
  },
  render: function () {
    var display = "";
    if (this.state.records.length == 0) {
      display = "upload-progress-bars-hidden";
    }
    return (
        <div className={"upload-progress-bars panel panel-warning " + display}>
          <div className="panel-heading">Upload Progress</div>
          <div className="panel-body upload-progress-panel-body">
          {
            this.state.records.map(function (record) {
              if (record.error) {
                return <ErrorBar progress={this} record={record} />;
              } else {
                return <ProgressBar record={record} />;
              }
            }.bind(this))
          }
          </div>
        </div>
    );
  }
});

var ProgressBar = React.createClass({
  render: function () {
    return (
        <div className="progress">
          <div className="progress-bar upload-progress-bar"
            id={this.props.record.id} role="progressbar"
            aria-valuenow="0" aria-valuemin="0" aria-valuemax="100">
            <span className="percent">0%</span> - {this.props.record.filename}
          </div>
        </div>
    );
  }
});

var ErrorBar = React.createClass({
  onCloseClicked: function () {
    this.props.progress.removeRecord(this.props.record.id);
  },
  render: function () {
    return (
        <div className="progress-error">
          <div className="alert alert-danger upload-alert">
            <button type="button" className="close" aria-label="Close"
              onClick={this.onCloseClicked}>
              <span aria-hidden="true">&times;</span>
            </button>
            <b>{this.props.record.filename}</b><br />
              {this.props.record.message}
          </div>
        </div>
    );
  }
});
